name: Aylik Fikstur Botu

on:
  workflow_dispatch: # İstediğin zaman elle çalıştırmanı sağlar
  schedule:
    - cron: '0 9 1 * *' # Her ayın 1. günü Türkiye saatiyle öğlen civarı çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kodu Calistir
        run: python ana_kod.py

      - name: Excel'i Kaydet ve Yukle
        run: |
          git config --global user.name 'Fikstur Botu'
          git config --global user.email 'bot@github.com'
          git pull origin main # Önce buluttaki son hali çek
          git add maclarim.xlsx
          git commit -m "Yeni ayın fikstürü güncellendi" || echo "Değişiklik yok"
          git push origin main
